# ACTIVIDAD 1

#### Importamos las librerias correspondientes

In [1]:
# Librerías de Python para la manipulación de datos
import pandas as pd
import numpy as np

# Para la visualización de datos
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns
import plotly.express as px

### Visualizamos y agregamos las cabeceras del dataset

In [2]:
df = pd.read_csv("processed.cleveland.data",names =["age", "sex", "cp","trestbps","chol","fbs", "restecg", "thalach", "exang","oldpeak","slope", "ca", "thal", "num"])
df.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  num  
0    3.0  0.0  6.0    0  
1    2.0  3.0  3.0    2  
2    2.0  2.0  7.0    1  
3    3.0  0.0  3.0    0  
4    1.0  0.0  3.0    0

### Señalamos las variables numericas

In [10]:
df._get_numeric_data().head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope  num  
0    3.0    0  
1    2.0    2  
2    2.0    1  
3    3.0    0  
4    1.0    0

Si bien tenemos las variables "numericas" con la sentencia antes ejecutada, podemos deducir leyendo el archivo "heart-disease.names" que las variables numericas son: age, trestbps, chol, thalach, oldpeak.

### Señalamos las variables continuas y discretas

##### AGE

In [11]:
df['age'].unique()

array([63., 67., 37., 41., 56., 62., 57., 53., 44., 52., 48., 54., 49.,
       64., 58., 60., 50., 66., 43., 40., 69., 59., 42., 55., 61., 65.,
       71., 51., 46., 45., 39., 68., 47., 34., 35., 29., 70., 77., 38.,
       74., 76.])

La variable edad se considera DISCRETA porque los datos de edad no tienen valores decimales

##### TRESTBPS

In [12]:
df['trestbps'].unique()

array([145., 160., 120., 130., 140., 172., 150., 110., 132., 117., 135.,
       112., 105., 124., 125., 142., 128., 170., 155., 104., 180., 138.,
       108., 134., 122., 115., 118., 100., 200.,  94., 165., 102., 152.,
       101., 126., 174., 148., 178., 158., 192., 129., 144., 123., 136.,
       146., 106., 156., 154., 114., 164.])

La variable trestbps se considera DISCRETA porque los datos de trestbps no tienen valores decimales

##### CHOL

In [13]:
df['chol'].unique()

array([233., 286., 229., 250., 204., 236., 268., 354., 254., 203., 192.,
       294., 256., 263., 199., 168., 239., 275., 266., 211., 283., 284.,
       224., 206., 219., 340., 226., 247., 167., 230., 335., 234., 177.,
       276., 353., 243., 225., 302., 212., 330., 175., 417., 197., 198.,
       290., 253., 172., 273., 213., 305., 216., 304., 188., 282., 185.,
       232., 326., 231., 269., 267., 248., 360., 258., 308., 245., 270.,
       208., 264., 321., 274., 325., 235., 257., 164., 141., 252., 255.,
       201., 222., 260., 182., 303., 265., 309., 307., 249., 186., 341.,
       183., 407., 217., 288., 220., 209., 227., 261., 174., 281., 221.,
       205., 240., 289., 318., 298., 564., 246., 322., 299., 300., 293.,
       277., 214., 207., 223., 160., 394., 184., 315., 409., 244., 195.,
       196., 126., 313., 259., 200., 262., 215., 228., 193., 271., 210.,
       327., 149., 295., 306., 178., 237., 218., 242., 319., 166., 180.,
       311., 278., 342., 169., 187., 157., 176., 24

La variable chol se considera DISCRETA porque los datos de chol no tienen valores decimales

##### THALACH

In [14]:
df['thalach'].unique()

array([150., 108., 129., 187., 172., 178., 160., 163., 147., 155., 148.,
       153., 142., 173., 162., 174., 168., 139., 171., 144., 132., 158.,
       114., 151., 161., 179., 120., 112., 137., 157., 169., 165., 123.,
       128., 152., 140., 188., 109., 125., 131., 170., 113.,  99., 177.,
       141., 180., 111., 143., 182., 156., 115., 149., 145., 146., 175.,
       186., 185., 159., 130., 190., 136.,  97., 127., 154., 133., 126.,
       202., 103., 166., 164., 184., 124., 122.,  96., 138.,  88., 105.,
       194., 195., 106., 167.,  95., 192., 117., 121., 116.,  71., 118.,
       181., 134.,  90.])

La variable thalach se considera DISCRETA porque los datos de thalach no tienen valores decimales

##### OLDPEAK

In [15]:
df['oldpeak'].unique()

array([2.3, 1.5, 2.6, 3.5, 1.4, 0.8, 3.6, 0.6, 3.1, 0.4, 1.3, 0. , 0.5,
       1.6, 1. , 1.2, 0.2, 1.8, 3.2, 2.4, 2. , 2.5, 2.2, 2.8, 3. , 3.4,
       6.2, 4. , 5.6, 2.9, 0.1, 2.1, 1.9, 4.2, 0.9, 1.1, 3.8, 0.7, 0.3,
       4.4])

La variable oldpeak se considera CONTINUA porque los datos de oldpeak tienen valores decimales

### Señalamos las variables categoricas

In [16]:
df.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca thal  num  
0    3.0  0.0  6.0    0  
1    2.0  3.0  3.0    2  
2    2.0  2.0  7.0    1  
3    3.0  0.0  3.0    0  
4    1.0  0.0  3.0    0

Aqui tenemos todas las variables del dataset, podemos deducir leyendo el archivo "heart-disease.names" que las variables categoricas son: sex, cp, fbs, exang, slope, thal, num.

### Señalamos las variables ordinales y nominales

##### SEX

In [20]:
df['sex'].unique()

array([1., 0.])

La variable sex es NOMINAL; ya que puede variar el orden de sus valores y el concepto de la variable no cambiaria.

##### CP

In [22]:
df['cp'].unique()

array([1., 4., 3., 2.])

La variable cp es ORDINAL; ya que no puede variar el orden de sus valores y el concepto de la variable cambiaria.

##### FBS

In [23]:
df['fbs'].unique()

array([1., 0.])

La variable fbs es NOMINAL; ya que puede variar el orden de sus valores y el concepto de la variable no cambiaria.

##### EXANG

In [24]:
df['exang'].unique()

array([0., 1.])

La variable exang es NOMINAL; ya que puede variar el orden de sus valores y el concepto de la variable no cambiaria.

##### THAL

In [27]:
df['thal'].unique()

array(['6.0', '3.0', '7.0', '?'], dtype=object)

La variable thal es NOMINAL; ya que puede variar el orden de sus valores y el concepto de la variable no cambiaria.

##### NUM

In [28]:
df['num'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

La variable num es NOMINAL; ya que puede variar el orden de sus valores y el concepto de la variable no cambiaria. Considerar que si es diferente de "cero" se clasifica 